name: Rokae
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.12.2=h06a4308_0
  - expat=2.7.3=h7354ed3_4
  - ld_impl_linux-64=2.44=h153f514_2
  - libexpat=2.7.3=h7354ed3_4
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgomp=15.2.0=h4751f2c_7
  - libnsl=2.0.0=h5eee18b_0
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - ncurses=6.5=h7934f7d_0
  - openssl=3.0.18=hd6dcaed_0
  - pip=25.3=pyhc872135_0
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.10.19=h6fa692b_0
  - readline=8.3=hc2a1206_0
  - setuptools=80.9.0=py310h06a4308_0
  - sqlite=3.51.1=he0a8d7e_0
  - tk=8.6.15=h54e0aa7_0
  - wheel=0.45.1=py310h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - pip:
      - addict==2.4.0
      - annotated-types==0.7.0
      - anyio==4.12.1
      - asttokens==3.0.1
      - attrs==25.4.0
      - blinker==1.9.0
      - certifi==2022.12.7
      - charset-normalizer==2.1.1
      - click==8.3.1
      - comm==0.2.3
      - configargparse==1.7.1
      - contourpy==1.3.2
      - cycler==0.12.1
      - cython==3.2.4
      - dash==3.3.0
      - decorator==5.2.1
      - distro==1.9.0
      - exceptiongroup==1.3.1
      - executing==2.2.1
      - fastjsonschema==2.21.2
      - filelock==3.20.0
      - flask==3.1.2
      - fonttools==4.61.1
      - fsspec==2025.12.0
      - grasp-nms==1.0.2
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - idna==3.4
      - importlib-metadata==8.7.1
      - ipython==8.38.0
      - ipywidgets==8.1.8
      - itsdangerous==2.2.0
      - jedi==0.19.2
      - jinja2==3.1.6
      - jiter==0.12.0
      - joblib==1.5.3
      - jsonschema==4.26.0
      - jsonschema-specifications==2025.9.1
      - jupyter-core==5.9.1
      - jupyterlab-widgets==3.0.16
      - kiwisolver==1.4.9
      - knn-pytorch==0.1
      - markupsafe==2.1.5
      - matplotlib==3.10.8
      - matplotlib-inline==0.2.1
      - mpmath==1.3.0
      - narwhals==2.15.0
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.4.2
      - numpy==1.24.4
      - open3d==0.18.0
      - openai==2.15.0
      - opencv-python==4.11.0.86
      - packaging==25.0
      - pandas==2.3.3
      - parso==0.8.5
      - pexpect==4.9.0
      - pillow==12.0.0
      - platformdirs==4.5.1
      - plotly==6.5.1
      - pointnet2==0.0.0
      - prompt-toolkit==3.0.52
      - psutil==7.2.1
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - py-cpuinfo==9.0.0
      - pybullet==3.2.7
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pygments==2.19.2
      - pymodbus==3.11.4
      - pyparsing==3.3.1
      - pyquaternion==0.9.9
      - pyserial==3.5
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.3
      - referencing==0.37.0
      - requests==2.28.1
      - retrying==1.4.2
      - rpds-py==0.30.0
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - seaborn==0.13.2
      - six==1.17.0
      - sniffio==1.3.1
      - stack-data==0.6.3
      - sympy==1.14.0
      - threadpoolctl==3.6.0
      - torch==2.1.0+cu121
      - torchaudio==2.1.0+cu121
      - torchvision==0.16.0+cu121
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transforms3d==0.4.2
      - triton==2.1.0
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2025.3
      - ultralytics==8.2.32
      - ultralytics-thop==2.0.18
      - urllib3==1.26.13
      - wcwidth==0.2.14
      - werkzeug==3.1.5
      - widgetsnbextension==4.0.15
      - zipp==3.23.0
prefix: /home/martin/miniconda3/envs/Rokae
